### ISSUE TITLE
sunrise_call_action TypeError

### ISSUE THREAD

**Issue by jasonpstokes** [oziee/ha-solcast-solar#13]
Upgraded to 2.0.3 and on startup got this error?
```
Logger: custom_components.solcast_solar
Source: custom_components/solcast_solar/__init__.py:339
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 06:56:07 (1 occurrences)
Last logged: 06:56:07

sunrise_call_action: Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py", line 290, in sunrise_call_action ac = int(ac) TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by oziee** [comment]
Can you edit the init file and move line 70 two lines up above line 68 and restart HA and see if the error disappears

**Comment by del13r** [comment]
> @jasonpstokes Can you edit the init file and move line 70 two lines up above line 68 and restart HA and see if the error disappears

 Before
![image](https://user-images.githubusercontent.com/86141523/139618843-954aa438-eb38-4302-8d26-fd23e5f67dbe.png)

After
![image](https://user-images.githubusercontent.com/86141523/139618870-82f312d0-da0f-4d4a-87b0-3433057312ae.png)

After reboot
`2021-11-01 14:44:41 DEBUG (MainThread) [custom_components.solcast_solar] Setting up Solcast for rooftop id XXXX-XXXX-XXXX-XXXX
2021-11-01 14:44:41 DEBUG (MainThread) [custom_components.solcast_solar] registering API limit reset
2021-11-01 14:44:41 DEBUG (MainThread) [custom_components.solcast_solar] registering daily forecast update at 00:00:00
2021-11-01 14:44:42 DEBUG (MainThread) [custom_components.solcast_solar] registered forecast_today sensor sensor.solcast_forecast_today
2021-11-01 14:44:42 DEBUG (MainThread) [custom_components.solcast_solar] registered forecast_today_remaining sensor sensor.solcast_forecast_today_remaining
2021-11-01 14:44:42 DEBUG (MainThread) [custom_components.solcast_solar] registered forecast_tomorrow sensor sensor.solcast_forecast_tomorrow
2021-11-01 14:44:42 DEBUG (MainThread) [custom_components.solcast_solar] registered API count sensor sensor.solcast_remaining_api_count
2021-11-01 14:44:42 DEBUG (MainThread) [custom_components.solcast_solar] registered last_update sensor sensor.solcast_last_updated
2021-11-01 14:44:42 DEBUG (MainThread) [custom_components.solcast_solar] No updates to schedule for today. Sunset already. Will create a new schedule at sunrise tomorrow. You can use the Solcast PV Forecast: update_forecast service call to get call the API right now.`

**Comment by oziee** [comment]
Cool so seems to solve that error.. but as you can see it's hit the bug I saw this morning that I have fixed in my system that I will have to PR tonight

**Comment by del13r** [comment]
> Cool so seems to solve that error.. but as you can see it's hit the bug I saw this morning that I have fixed in my system that I will have to PR tonight

Cheers, however It seems to mistakenly think the sun has set for the day.

2021-11-01 14:44:42 DEBUG (MainThread) [custom_components.solcast_solar] No updates to schedule for today. Sunset already. Will create a new schedule at sunrise tomorrow. You can use the Solcast PV Forecast: update_forecast service call to get call the API right now.

**Comment by oziee** [comment]
V2.0.4 should fix this

**Comment by jasonpstokes** [comment]
Thanks @oziee. Was away all day from my computer so couldn't try your fix earlier, sorry.

Does the package contain the updated version though? I've just updated from HACS and then also tried manually (from the [release](https://github.com/oziee/ha-solcast-solar/releases/tag/V2.0.4)) - but I'm still getting the error on start-up?

**Comment by oziee** [comment]
Yeah I think I'll wait till I get home and do it properly instead of on my phone 

I did miss something
