### ISSUE TITLE
This hour and next value is 0

### ISSUE THREAD

**Issue by oziee** [oziee/ha-solcast-solar#41]
Known problem.. will fix soon

**Comment by oziee** [comment]
should be fixed in 3.0.5

**Comment by oziee** [comment]
still sometimes happening.. working it out still

**Comment by oziee** [comment]
Have submitted a support ticket to Solcast as the API is not always returning a full data set which is what is causing this problem

**Comment by gedger** [comment]
I presume that these will still not be valid for those with 2 roofs as the API is only polled every 2 hours to stop hitting the API limit?

I was wondering  if there is any scope to poll the API every hour for the call that updates these and every 2 hours for the other?

With 48 API calls per day then 3 per hour would give 16 hours of data which would almost make the full day? I'm current generating for 17 hours so would loose the last hour which I don't think thats an issue for most?

**Comment by oziee** [comment]
@gedger im not 100% sure what your asking but hope this answer helps..

the next version will 
-poll for the forecast data midnight, hour of sunrise, every hour till sunset hour
-poll for actual past data between sunrise and sunset every even hour

if ppl have more than 2 rooftop sites in the toolkit and they run out of api calls it would not really matter as it will still display the 'forecast' data until the api counter resets at UTC midnight

**Comment by gedger** [comment]
Thanks for the clarification, I explained the suggestion badly......

I'll have another go, 2 API calls are made per roof, one for the forecast and one for the past data. I believe the forecast  to be significantly more important than updating what's happened, I already know what actually happened from my Solar output. I therefore suggest that the actual past data is polled every 3 hours whereas the more important forecast is polled every hour.

Using the next version mythology for someone at my latitude with 2 roofs who gets Solar from 4:30am to 10:15pm ~ 18 hours

Start with 48 polls.
Midnight Poll leaves 44 Polls
Sunrise start poll (4:30) 40 Polls Left
API calls left is 40 or 10 hours
Therefore I will have no data for 8 hours.

I hope this makes more sense or have I completely missed the point?

**Comment by gedger** [comment]
I just double checked this and it does just fit in for me but will still break for someone on higher latitudes than me?
```
Time	API	Total
12:00	2
04:30 	2
05:30 	2
06:30 	4 	10
07:30 	2
08:30 	2
09:30 	4 	18
10:30 	2
11:30 	2
12:30 	4	26
13:30 	2
14:30 	2
15:30 	4	34
16:30 	2
17:30 	2
18:30 	4	42
19:30 	2
20:30 	2
21:30 	4	48
22:30 	2	break
```

**Comment by oziee** [comment]
check now
